In [5]:
import numpy as np
array=np.zeros((3,2))
print(array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
import numpy as np
array=np.ones((3,2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
import numpy as np
array=np.eye(4)
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
import numpy as np
array=np.eye(3,4)
print(array)
np.diag(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


array([1., 1., 1.])

In [15]:
import numpy as np
array=np.diag([3,4,5,6])
print(array)

[[3 0 0 0]
 [0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]]


In [17]:
print("Hello")

Hello


In [20]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
value=arr>5
aray=arr[value].copy()
aray

array([ 6,  7,  8,  9, 10])

In [37]:
arr

aray


array([ 6,  7,  8,  9, 10])

In [39]:
a=arr[arr<4]

In [40]:
a


array([1, 2, 3])

In [41]:
a=arr[arr%2==0]

In [42]:
a


array([ 2,  4,  6,  8, 10])

In [46]:
a=arr[arr==5]=15
a

15

In [47]:
arr

array([ 1,  2,  3,  4, 15,  6,  7,  8,  9, 10])

In [70]:
arr[arr%2==0]

array([2, 2, 2, 2, 2])

In [68]:
a
a=0
a
arr

array([ 1,  2,  3,  2, 15,  2,  7,  2,  9,  2])

In [71]:
arr

array([ 1,  2,  3,  2, 15,  2,  7,  2,  9,  2])

In [72]:
print("Hello")

Hello


In [80]:
np.random.seed(10)
mat1=np.random.randint(1,26,(5,5))
mat2=np.random.randint(1,26,(5,5))

print(mat2)

[[10  5 16  1 18]
 [17 18  9 10  1]
 [11  9 23  5 20]
 [17  5 16 12 23]
 [25 12  2  9  5]]
[[15 18 20 23 14]
 [ 6 14 20 14 23]
 [13  2  5 19 14]
 [23 24 25 12 11]
 [25 10 16 19 17]]


In [81]:
print(mat1)

[[10  5 16  1 18]
 [17 18  9 10  1]
 [11  9 23  5 20]
 [17  5 16 12 23]
 [25 12  2  9  5]]


In [82]:
print(mat2)

[[15 18 20 23 14]
 [ 6 14 20 14 23]
 [13  2  5 19 14]
 [23 24 25 12 11]
 [25 10 16 19 17]]


In [84]:
print(mat1.dot(mat2))

[[ 861  486  693  958  796]
 [ 735  826 1011  953  905]
 [1133  690  960 1256 1078]
 [1344  926 1188 1346 1100]
 [ 805  888 1055  984  838]]


In [85]:
print(mat2.dot(mat1))

[[1417  862 1258  697 1287]
 [1331  808  952  621  959]
 [ 892  409  673  412  843]
 [1392  964 1373  631 1269]
 [1344  748 1196  586 1302]]


In [92]:
#print(mat1.dot(mat2)==mat2.dot(mat1))
if((mat1.dot(mat2)).any()==(mat2.dot(mat1)).any()):
    print("True")
else:
    print("False")

True


In [94]:
mat1

array([[10,  5, 16,  1, 18],
       [17, 18,  9, 10,  1],
       [11,  9, 23,  5, 20],
       [17,  5, 16, 12, 23],
       [25, 12,  2,  9,  5]])

In [95]:
mat2

array([[15, 18, 20, 23, 14],
       [ 6, 14, 20, 14, 23],
       [13,  2,  5, 19, 14],
       [23, 24, 25, 12, 11],
       [25, 10, 16, 19, 17]])

In [96]:
np.min(mat1)

1

In [98]:
np.max(mat1)

25

In [99]:

np.argmin(mat1)

3

In [100]:
np.argmax(mat1)

20

In [106]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Bhawesh\\Desktop\\100 Sales Records.csv")
df
print(df.shape)

(100, 14)


In [108]:
#data frame using dictionary
dictio={
   'Region':['Australia and Oceania','Central America and the Caribbean','Europe', 'Sub-Saharan Africa', 'Sub-Saharan Africa',],
   'Country':['Tuvalu','Grenada','Rwanda', 'Russia', 'Sao Tome and Principe',],
   'Item Type':['Baby Food','Cereal	','Fruits', 'Office Supplies', 'Office Supplies',],
   'Sales Channel':['Offline','Online','Offline', 'Online', 'Offline',],
   'Order Priority':['H','C','L', 'C', 'L',],
   'Order Date':['5/28/2010','8/22/2012','5/2/2014', '6/20/2014', '2/1/2013',],
   'Order ID':['669165933','963881480','341417157', '514321792', '115456712',],
}
df_dict=pd.DataFrame(dictio)
df_dict

Region                Country        Item Type  \
0              Australia and Oceania                 Tuvalu        Baby Food   
1  Central America and the Caribbean                Grenada         Cereal\t   
2                             Europe                 Rwanda           Fruits   
3                 Sub-Saharan Africa                 Russia  Office Supplies   
4                 Sub-Saharan Africa  Sao Tome and Principe  Office Supplies   

  Sales Channel Order Priority Order Date   Order ID  
0       Offline              H  5/28/2010  669165933  
1        Online              C  8/22/2012  963881480  
2       Offline              L   5/2/2014  341417157  
3        Online              C  6/20/2014  514321792  
4       Offline              L   2/1/2013  115456712

In [110]:
print(df_dict.shape)

(5, 7)


In [111]:
rows,column=df.shape
print(rows)
print(column)

100
14


In [117]:
df_head=df.head()
df_head

Region                Country        Item Type  \
0              Australia and Oceania                 Tuvalu        Baby Food   
1  Central America and the Caribbean                Grenada           Cereal   
2                             Europe                 Russia  Office Supplies   
3                 Sub-Saharan Africa  Sao Tome and Principe           Fruits   
4                 Sub-Saharan Africa                 Rwanda  Office Supplies   

  Sales Channel Order Priority Order Date   Order ID  Ship Date  Units Sold  \
0       Offline              H  5/28/2010  669165933  6/27/2010        9925   
1        Online              C  8/22/2012  963881480  9/15/2012        2804   
2       Offline              L   5/2/2014  341417157   5/8/2014        1779   
3        Online              C  6/20/2014  514321792   7/5/2014        8102   
4       Offline              L   2/1/2013  115456712   2/6/2013        5062   

   Unit Price  Unit Cost  Total Revenue  Total Cost  Total Profit  
0      255.28     159.42     2533654.00  1582243.50     951410.50  
1      205.70     117.11      576782.80   328376.44     248406.36  
2      651.21     524.96     1158502.59   933903.84     224598.75  
3        9.33       6.92       75591.66    56065.84      19525.82  
4      651.21     524.96     3296425.02  2657347.52     639077.50

In [121]:
df_head=df.head(0)
df_head

Empty DataFrame
Columns: [Region, Country, Item Type, Sales Channel, Order Priority, Order Date, Order ID, Ship Date, Units Sold, Unit Price, Unit Cost, Total Revenue, Total Cost, Total Profit]
Index: []

In [125]:
df_head=df.tail(5)
df_head

Region       Country      Item Type Sales Channel  \
95  Sub-Saharan Africa          Mali        Clothes        Online   
96                Asia      Malaysia         Fruits       Offline   
97  Sub-Saharan Africa  Sierra Leone     Vegetables       Offline   
98       North America        Mexico  Personal Care       Offline   
99  Sub-Saharan Africa    Mozambique      Household       Offline   

   Order Priority  Order Date   Order ID   Ship Date  Units Sold  Unit Price  \
95              M   7/26/2011  512878119    9/3/2011         888      109.28   
96              L  11/11/2011  810711038  12/28/2011        6267        9.33   
97              C    6/1/2016  728815257   6/29/2016        1485      154.06   
98              M   7/30/2015  559427106    8/8/2015        5767       81.73   
99              L   2/10/2012  665095412   2/15/2012        5367      668.27   

    Unit Cost  Total Revenue  Total Cost  Total Profit  
95      35.84       97040.64    31825.92      65214.72  
96       6.92       58471.11    43367.64      15103.47  
97      90.93      228779.10   135031.05      93748.05  
98      56.67      471336.91   326815.89     144521.02  
99     502.54     3586605.09  2697132.18     889472.91

In [128]:
df[2:5]

Region                Country        Item Type Sales Channel  \
2              Europe                 Russia  Office Supplies       Offline   
3  Sub-Saharan Africa  Sao Tome and Principe           Fruits        Online   
4  Sub-Saharan Africa                 Rwanda  Office Supplies       Offline   

  Order Priority Order Date   Order ID Ship Date  Units Sold  Unit Price  \
2              L   5/2/2014  341417157  5/8/2014        1779      651.21   
3              C  6/20/2014  514321792  7/5/2014        8102        9.33   
4              L   2/1/2013  115456712  2/6/2013        5062      651.21   

   Unit Cost  Total Revenue  Total Cost  Total Profit  
2     524.96     1158502.59   933903.84     224598.75  
3       6.92       75591.66    56065.84      19525.82  
4     524.96     3296425.02  2657347.52     639077.50

In [133]:
df.columns

Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority',
       'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price',
       'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit'],
      dtype='object')

In [136]:
df['Region']

0                 Australia and Oceania
1     Central America and the Caribbean
2                                Europe
3                    Sub-Saharan Africa
4                    Sub-Saharan Africa
                    ...                
95                   Sub-Saharan Africa
96                                 Asia
97                   Sub-Saharan Africa
98                        North America
99                   Sub-Saharan Africa
Name: Region, Length: 100, dtype: object

In [138]:
df[['Region','Country']]

Region                Country
0               Australia and Oceania                 Tuvalu
1   Central America and the Caribbean                Grenada
2                              Europe                 Russia
3                  Sub-Saharan Africa  Sao Tome and Principe
4                  Sub-Saharan Africa                 Rwanda
..                                ...                    ...
95                 Sub-Saharan Africa                   Mali
96                               Asia               Malaysia
97                 Sub-Saharan Africa           Sierra Leone
98                      North America                 Mexico
99                 Sub-Saharan Africa             Mozambique

[100 rows x 2 columns]

In [139]:
df_head=df.tail(5)
df_head[['Region','Country']]

Region       Country
95  Sub-Saharan Africa          Mali
96                Asia      Malaysia
97  Sub-Saharan Africa  Sierra Leone
98       North America        Mexico
99  Sub-Saharan Africa    Mozambique

In [146]:
df['Units Sold'].max()

9925

In [147]:
df['Units Sold'].min()

124

In [148]:
df['Units Sold'].mean()

5128.71

In [150]:
df['Units Sold'].std()

2794.4845616956904

In [151]:
df.describe()

Order ID   Units Sold  Unit Price   Unit Cost  Total Revenue  \
count  1.000000e+02   100.000000  100.000000  100.000000   1.000000e+02   
mean   5.550204e+08  5128.710000  276.761300  191.048000   1.373488e+06   
std    2.606153e+08  2794.484562  235.592241  188.208181   1.460029e+06   
min    1.146066e+08   124.000000    9.330000    6.920000   4.870260e+03   
25%    3.389225e+08  2836.250000   81.730000   35.840000   2.687212e+05   
50%    5.577086e+08  5382.500000  179.880000  107.275000   7.523144e+05   
75%    7.907551e+08  7369.000000  437.200000  263.330000   2.212045e+06   
max    9.940222e+08  9925.000000  668.270000  524.960000   5.997055e+06   

         Total Cost  Total Profit  
count  1.000000e+02  1.000000e+02  
mean   9.318057e+05  4.416820e+05  
std    1.083938e+06  4.385379e+05  
min    3.612240e+03  1.258020e+03  
25%    1.688680e+05  1.214436e+05  
50%    3.635664e+05  2.907680e+05  
75%    1.613870e+06  6.358288e+05  
max    4.509794e+06  1.719922e+06

In [165]:
df2=df[df['Units Sold']==df['Units Sold'].max()]
df2[['Total Revenue','Total Cost','Total Profit']]


Total Revenue  Total Cost  Total Profit
0      2533654.0   1582243.5      951410.5

In [166]:
df2=df[df['Units Sold']==9925.000000]
df2[['Total Revenue','Total Cost','Total Profit']]

Total Revenue  Total Cost  Total Profit
0      2533654.0   1582243.5      951410.5

In [170]:
df.index
df.set_index('Order Date')

Region                Country  \
Order Date                                                             
5/28/2010               Australia and Oceania                 Tuvalu   
8/22/2012   Central America and the Caribbean                Grenada   
5/2/2014                               Europe                 Russia   
6/20/2014                  Sub-Saharan Africa  Sao Tome and Principe   
2/1/2013                   Sub-Saharan Africa                 Rwanda   
...                                       ...                    ...   
7/26/2011                  Sub-Saharan Africa                   Mali   
11/11/2011                               Asia               Malaysia   
6/1/2016                   Sub-Saharan Africa           Sierra Leone   
7/30/2015                       North America                 Mexico   
2/10/2012                  Sub-Saharan Africa             Mozambique   

                  Item Type Sales Channel Order Priority   Order ID  \
Order Date                                                            
5/28/2010         Baby Food       Offline              H  669165933   
8/22/2012            Cereal        Online              C  963881480   
5/2/2014    Office Supplies       Offline              L  341417157   
6/20/2014            Fruits        Online              C  514321792   
2/1/2013    Office Supplies       Offline              L  115456712   
...                     ...           ...            ...        ...   
7/26/2011           Clothes        Online              M  512878119   
11/11/2011           Fruits       Offline              L  810711038   
6/1/2016         Vegetables       Offline              C  728815257   
7/30/2015     Personal Care       Offline              M  559427106   
2/10/2012         Household       Offline              L  665095412   

             Ship Date  Units Sold  Unit Price  Unit Cost  Total Revenue  \
Order Date                                                                 
5/28/2010    6/27/2010        9925      255.28     159.42     2533654.00   
8/22/2012    9/15/2012        2804      205.70     117.11      576782.80   
5/2/2014      5/8/2014        1779      651.21     524.96     1158502.59   
6/20/2014     7/5/2014        8102        9.33       6.92       75591.66   
2/1/2013      2/6/2013        5062      651.21     524.96     3296425.02   
...                ...         ...         ...        ...            ...   
7/26/2011     9/3/2011         888      109.28      35.84       97040.64   
11/11/2011  12/28/2011        6267        9.33       6.92       58471.11   
6/1/2016     6/29/2016        1485      154.06      90.93      228779.10   
7/30/2015     8/8/2015        5767       81.73      56.67      471336.91   
2/10/2012    2/15/2012        5367      668.27     502.54     3586605.09   

            Total Cost  Total Profit  
Order Date                            
5/28/2010   1582243.50     951410.50  
8/22/2012    328376.44     248406.36  
5/2/2014     933903.84     224598.75  
6/20/2014     56065.84      19525.82  
2/1/2013    2657347.52     639077.50  
...                ...           ...  
7/26/2011     31825.92      65214.72  
11/11/2011    43367.64      15103.47  
6/1/2016     135031.05      93748.05  
7/30/2015    326815.89     144521.02  
2/10/2012   2697132.18     889472.91  

[100 rows x 13 columns]

# dataframe using xls files 

In [171]:
df_xl=pd.read_excel("C:\\Users\\Bhawesh\\Downloads\\Final Summer Internship.xlsx")
df_xl

S.N.   Student ID                 Name  \
0      1  2017UCS0031      AAYUSH SUGANDHI   
1      2  2017UCS0032   ABHIJEET AGNIHOTRI   
2      3  2017UCS0033    ABHINAV CHAUDHARY   
3      4  2017UCS0035        ADITYA NARESH   
4      5  2017UCS0036          AKASH KUMAR   
..   ...          ...                  ...   
91    92  2017UCE0028  SHREYAS ARVIND GORE   
92    93  2017UCE0030                VIVEK   
93    94  2017UCE0090    VINOD KUMAR MEENA   
94    95  2017UCE0109          PAVAN MEENA   
95    96  2017UCE0112     SHIV KUMAR MEENA   

               Final Internship (Name of the Company)  \
0                                          Prithvi.Ai   
1                                        LTI Infotech   
2   Inhouse internship under Dr. Yamuna Prasad Shukla   
3                               Macksofy Technologies   
4                                       Peacock Solar   
..                                                ...   
91                                                NaN   
92                                                NaN   
93  In house internship under Dr. Ankit Kathuria (...   
94  In house internship under Dr. Ankit Kathuria (...   
95  In house internship under Dr. Ankit Kathuria (...   

   Second Internship (If any)  
0                         NaN  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
91                        NaN  
92                        NaN  
93                        NaN  
94                        NaN  
95                        NaN  

[96 rows x 5 columns]

In [172]:
df_xl=pd.read_excel("C:\\Users\\Bhawesh\\Downloads\\Final Summer Internship.xlsx",skiprows=1)
df_xl

1  2017UCS0031      AAYUSH SUGANDHI  \
0    2  2017UCS0032   ABHIJEET AGNIHOTRI   
1    3  2017UCS0033    ABHINAV CHAUDHARY   
2    4  2017UCS0035        ADITYA NARESH   
3    5  2017UCS0036          AKASH KUMAR   
4    6  2017UCS0037          AYUSH HEDAU   
..  ..          ...                  ...   
90  92  2017UCE0028  SHREYAS ARVIND GORE   
91  93  2017UCE0030                VIVEK   
92  94  2017UCE0090    VINOD KUMAR MEENA   
93  95  2017UCE0109          PAVAN MEENA   
94  96  2017UCE0112     SHIV KUMAR MEENA   

                                           Prithvi.Ai Unnamed: 4  
0                                        LTI Infotech        NaN  
1   Inhouse internship under Dr. Yamuna Prasad Shukla        NaN  
2                               Macksofy Technologies        NaN  
3                                       Peacock Solar        NaN  
4                                            Altiwebs        NaN  
..                                                ...        ...  
90                                                NaN        NaN  
91                                                NaN        NaN  
92  In house internship under Dr. Ankit Kathuria (...        NaN  
93  In house internship under Dr. Ankit Kathuria (...        NaN  
94  In house internship under Dr. Ankit Kathuria (...        NaN  

[95 rows x 5 columns]

In [173]:
df_xl=pd.read_excel("C:\\Users\\Bhawesh\\Downloads\\Final Summer Internship.xlsx",header=1)
df_xl

1  2017UCS0031      AAYUSH SUGANDHI  \
0    2  2017UCS0032   ABHIJEET AGNIHOTRI   
1    3  2017UCS0033    ABHINAV CHAUDHARY   
2    4  2017UCS0035        ADITYA NARESH   
3    5  2017UCS0036          AKASH KUMAR   
4    6  2017UCS0037          AYUSH HEDAU   
..  ..          ...                  ...   
90  92  2017UCE0028  SHREYAS ARVIND GORE   
91  93  2017UCE0030                VIVEK   
92  94  2017UCE0090    VINOD KUMAR MEENA   
93  95  2017UCE0109          PAVAN MEENA   
94  96  2017UCE0112     SHIV KUMAR MEENA   

                                           Prithvi.Ai Unnamed: 4  
0                                        LTI Infotech        NaN  
1   Inhouse internship under Dr. Yamuna Prasad Shukla        NaN  
2                               Macksofy Technologies        NaN  
3                                       Peacock Solar        NaN  
4                                            Altiwebs        NaN  
..                                                ...        ...  
90                                                NaN        NaN  
91                                                NaN        NaN  
92  In house internship under Dr. Ankit Kathuria (...        NaN  
93  In house internship under Dr. Ankit Kathuria (...        NaN  
94  In house internship under Dr. Ankit Kathuria (...        NaN  

[95 rows x 5 columns]

In [178]:
df_xl=pd.read_excel("C:\\Users\\Bhawesh\\Downloads\\Final Summer Internship.xlsx",skiprows=1,header=None,names=["Serial number","Enrollment No.","Name","Internship1","Internship2"])
df_xl

Serial number Enrollment No.                 Name  \
0               1    2017UCS0031      AAYUSH SUGANDHI   
1               2    2017UCS0032   ABHIJEET AGNIHOTRI   
2               3    2017UCS0033    ABHINAV CHAUDHARY   
3               4    2017UCS0035        ADITYA NARESH   
4               5    2017UCS0036          AKASH KUMAR   
..            ...            ...                  ...   
91             92    2017UCE0028  SHREYAS ARVIND GORE   
92             93    2017UCE0030                VIVEK   
93             94    2017UCE0090    VINOD KUMAR MEENA   
94             95    2017UCE0109          PAVAN MEENA   
95             96    2017UCE0112     SHIV KUMAR MEENA   

                                          Internship1 Internship2  
0                                          Prithvi.Ai         NaN  
1                                        LTI Infotech         NaN  
2   Inhouse internship under Dr. Yamuna Prasad Shukla         NaN  
3                               Macksofy Technologies         NaN  
4                                       Peacock Solar         NaN  
..                                                ...         ...  
91                                                NaN         NaN  
92                                                NaN         NaN  
93  In house internship under Dr. Ankit Kathuria (...         NaN  
94  In house internship under Dr. Ankit Kathuria (...         NaN  
95  In house internship under Dr. Ankit Kathuria (...         NaN  

[96 rows x 5 columns]

In [179]:
df


Region                Country        Item Type  \
0               Australia and Oceania                 Tuvalu        Baby Food   
1   Central America and the Caribbean                Grenada           Cereal   
2                              Europe                 Russia  Office Supplies   
3                  Sub-Saharan Africa  Sao Tome and Principe           Fruits   
4                  Sub-Saharan Africa                 Rwanda  Office Supplies   
..                                ...                    ...              ...   
95                 Sub-Saharan Africa                   Mali          Clothes   
96                               Asia               Malaysia           Fruits   
97                 Sub-Saharan Africa           Sierra Leone       Vegetables   
98                      North America                 Mexico    Personal Care   
99                 Sub-Saharan Africa             Mozambique        Household   

   Sales Channel Order Priority  Order Date   Order ID   Ship Date  \
0        Offline              H   5/28/2010  669165933   6/27/2010   
1         Online              C   8/22/2012  963881480   9/15/2012   
2        Offline              L    5/2/2014  341417157    5/8/2014   
3         Online              C   6/20/2014  514321792    7/5/2014   
4        Offline              L    2/1/2013  115456712    2/6/2013   
..           ...            ...         ...        ...         ...   
95        Online              M   7/26/2011  512878119    9/3/2011   
96       Offline              L  11/11/2011  810711038  12/28/2011   
97       Offline              C    6/1/2016  728815257   6/29/2016   
98       Offline              M   7/30/2015  559427106    8/8/2015   
99       Offline              L   2/10/2012  665095412   2/15/2012   

    Units Sold  Unit Price  Unit Cost  Total Revenue  Total Cost  Total Profit  
0         9925      255.28     159.42     2533654.00  1582243.50     951410.50  
1         2804      205.70     117.11      576782.80   328376.44     248406.36  
2         1779      651.21     524.96     1158502.59   933903.84     224598.75  
3         8102        9.33       6.92       75591.66    56065.84      19525.82  
4         5062      651.21     524.96     3296425.02  2657347.52     639077.50  
..         ...         ...        ...            ...         ...           ...  
95         888      109.28      35.84       97040.64    31825.92      65214.72  
96        6267        9.33       6.92       58471.11    43367.64      15103.47  
97        1485      154.06      90.93      228779.10   135031.05      93748.05  
98        5767       81.73      56.67      471336.91   326815.89     144521.02  
99        5367      668.27     502.54     3586605.09  2697132.18     889472.91  

[100 rows x 14 columns]

In [180]:
df_xl

Serial number Enrollment No.                 Name  \
0               1    2017UCS0031      AAYUSH SUGANDHI   
1               2    2017UCS0032   ABHIJEET AGNIHOTRI   
2               3    2017UCS0033    ABHINAV CHAUDHARY   
3               4    2017UCS0035        ADITYA NARESH   
4               5    2017UCS0036          AKASH KUMAR   
..            ...            ...                  ...   
91             92    2017UCE0028  SHREYAS ARVIND GORE   
92             93    2017UCE0030                VIVEK   
93             94    2017UCE0090    VINOD KUMAR MEENA   
94             95    2017UCE0109          PAVAN MEENA   
95             96    2017UCE0112     SHIV KUMAR MEENA   

                                          Internship1 Internship2  
0                                          Prithvi.Ai         NaN  
1                                        LTI Infotech         NaN  
2   Inhouse internship under Dr. Yamuna Prasad Shukla         NaN  
3                               Macksofy Technologies         NaN  
4                                       Peacock Solar         NaN  
..                                                ...         ...  
91                                                NaN         NaN  
92                                                NaN         NaN  
93  In house internship under Dr. Ankit Kathuria (...         NaN  
94  In house internship under Dr. Ankit Kathuria (...         NaN  
95  In house internship under Dr. Ankit Kathuria (...         NaN  

[96 rows x 5 columns]

In [181]:
df_xl

Serial number Enrollment No.                 Name  \
0               1    2017UCS0031      AAYUSH SUGANDHI   
1               2    2017UCS0032   ABHIJEET AGNIHOTRI   
2               3    2017UCS0033    ABHINAV CHAUDHARY   
3               4    2017UCS0035        ADITYA NARESH   
4               5    2017UCS0036          AKASH KUMAR   
..            ...            ...                  ...   
91             92    2017UCE0028  SHREYAS ARVIND GORE   
92             93    2017UCE0030                VIVEK   
93             94    2017UCE0090    VINOD KUMAR MEENA   
94             95    2017UCE0109          PAVAN MEENA   
95             96    2017UCE0112     SHIV KUMAR MEENA   

                                          Internship1 Internship2  
0                                          Prithvi.Ai         NaN  
1                                        LTI Infotech         NaN  
2   Inhouse internship under Dr. Yamuna Prasad Shukla         NaN  
3                               Macksofy Technologies         NaN  
4                                       Peacock Solar         NaN  
..                                                ...         ...  
91                                                NaN         NaN  
92                                                NaN         NaN  
93  In house internship under Dr. Ankit Kathuria (...         NaN  
94  In house internship under Dr. Ankit Kathuria (...         NaN  
95  In house internship under Dr. Ankit Kathuria (...         NaN  

[96 rows x 5 columns]

In [183]:
df_xl.to_csv("new.csv")

In [184]:
df_xl.to_csv("C:\\Users\\Bhawesh\\Desktop\\new.csv")

In [189]:
print(df_xl.size)
print(df_xl.shape)


480
(96, 5)


In [192]:
print(type(df_xl))

<class 'pandas.core.frame.DataFrame'>


In [193]:
df_xl

Serial number Enrollment No.                 Name  \
0               1    2017UCS0031      AAYUSH SUGANDHI   
1               2    2017UCS0032   ABHIJEET AGNIHOTRI   
2               3    2017UCS0033    ABHINAV CHAUDHARY   
3               4    2017UCS0035        ADITYA NARESH   
4               5    2017UCS0036          AKASH KUMAR   
..            ...            ...                  ...   
91             92    2017UCE0028  SHREYAS ARVIND GORE   
92             93    2017UCE0030                VIVEK   
93             94    2017UCE0090    VINOD KUMAR MEENA   
94             95    2017UCE0109          PAVAN MEENA   
95             96    2017UCE0112     SHIV KUMAR MEENA   

                                          Internship1 Internship2  
0                                          Prithvi.Ai         NaN  
1                                        LTI Infotech         NaN  
2   Inhouse internship under Dr. Yamuna Prasad Shukla         NaN  
3                               Macksofy Technologies         NaN  
4                                       Peacock Solar         NaN  
..                                                ...         ...  
91                                                NaN         NaN  
92                                                NaN         NaN  
93  In house internship under Dr. Ankit Kathuria (...         NaN  
94  In house internship under Dr. Ankit Kathuria (...         NaN  
95  In house internship under Dr. Ankit Kathuria (...         NaN  

[96 rows x 5 columns]

In [194]:
df_xl[['Enrollment No.','Name']]

Enrollment No.                 Name
0     2017UCS0031      AAYUSH SUGANDHI
1     2017UCS0032   ABHIJEET AGNIHOTRI
2     2017UCS0033    ABHINAV CHAUDHARY
3     2017UCS0035        ADITYA NARESH
4     2017UCS0036          AKASH KUMAR
..            ...                  ...
91    2017UCE0028  SHREYAS ARVIND GORE
92    2017UCE0030                VIVEK
93    2017UCE0090    VINOD KUMAR MEENA
94    2017UCE0109          PAVAN MEENA
95    2017UCE0112     SHIV KUMAR MEENA

[96 rows x 2 columns]

In [208]:
df_xl.loc[0:6, ["Enrollment No.", "Name"]]

Enrollment No.                Name
0    2017UCS0031     AAYUSH SUGANDHI
1    2017UCS0032  ABHIJEET AGNIHOTRI
2    2017UCS0033   ABHINAV CHAUDHARY
3    2017UCS0035       ADITYA NARESH
4    2017UCS0036         AKASH KUMAR
5    2017UCS0037         AYUSH HEDAU
6    2017UCS0038  BHATRI NARAYANAN S

In [212]:
df_xl.Name.tail()

91    SHREYAS ARVIND GORE
92                  VIVEK
93      VINOD KUMAR MEENA
94            PAVAN MEENA
95       SHIV KUMAR MEENA
Name: Name, dtype: object

In [217]:
df_xl.loc[[10,20,30]]

Serial number Enrollment No.             Name  \
10             11    2017UCS0044       MANAS GHAI   
20             21    2017UCS0058           VISHNU   
30             31    2017UEE0064  AKHILESH SHARMA   

                                        Internship1 Internship2  
10  Inhouse Internship under Dr. Sumit Kumar Pandey         NaN  
20                                              JBM         NaN  
30                       Larsen and Toubro Infotech         NaN

In [218]:
df_xl.describe()

Serial number
count      96.000000
mean       48.500000
std        27.856777
min         1.000000
25%        24.750000
50%        48.500000
75%        72.250000
max        96.000000

In [220]:
df_xl.loc[[10,20,30],["Enrollment No.","Name"]]

Enrollment No.             Name
10    2017UCS0044       MANAS GHAI
20    2017UCS0058           VISHNU
30    2017UEE0064  AKHILESH SHARMA

In [222]:
df_xl.loc[10:15,["Enrollment No.","Name"]]

Enrollment No.           Name
10    2017UCS0044     MANAS GHAI
11    2017UCS0046   NIKHIL KUMAR
12    2017UCS0047  PARTH THAKKER
13    2017UCS0048  PRINCE SHUKLA
14    2017UCS0049    RAGHUNANDAN
15    2017UCS0050   RAJAT KHANNA

In [224]:
df_xl.loc[11:15,["Name"]]

Name
11   NIKHIL KUMAR
12  PARTH THAKKER
13  PRINCE SHUKLA
14    RAGHUNANDAN
15   RAJAT KHANNA

In [231]:
df_xl.iloc[[2,3],[2,3]]

Name                                        Internship1
2  ABHINAV CHAUDHARY  Inhouse internship under Dr. Yamuna Prasad Shukla
3      ADITYA NARESH                              Macksofy Technologies

In [233]:
df_xl.loc[[2,3,4,5,6], "Enrollment No.":"Internship1"]

Enrollment No.                Name  \
2    2017UCS0033   ABHINAV CHAUDHARY   
3    2017UCS0035       ADITYA NARESH   
4    2017UCS0036         AKASH KUMAR   
5    2017UCS0037         AYUSH HEDAU   
6    2017UCS0038  BHATRI NARAYANAN S   

                                         Internship1  
2  Inhouse internship under Dr. Yamuna Prasad Shukla  
3                              Macksofy Technologies  
4                                      Peacock Solar  
5                                           Altiwebs  
6                                                NaN