In [4]:
print("Hello")

Hello


### HI
--hbciac
--bvjacbj



In [18]:
import numpy as np
A=np.random.randint(10,size=(5,5))
print(A)

[[7 0 4 2 3]
 [1 7 7 8 1]
 [2 9 5 4 6]
 [2 5 3 1 6]
 [8 7 9 5 5]]


In [26]:
import numpy as np
B=np.random.randint(10,size=(5,5))
print(B)
print(B[2,2])
#print(A)

[[9 7 2 9 2]
 [5 9 9 7 1]
 [5 2 9 2 7]
 [5 4 9 7 6]
 [8 0 1 6 6]]
9


In [32]:
c=np.zeros((5,5),int)
print(c)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [33]:
for i in range(5):
    for j in range(5):
        c[i,j]=A[i,j]+B[i,j]
print(c)
print(A+B)
D=A+B


[[16  7  6 11  5]
 [ 6 16 16 15  2]
 [ 7 11 14  6 13]
 [ 7  9 12  8 12]
 [16  7 10 11 11]]
[[16  7  6 11  5]
 [ 6 16 16 15  2]
 [ 7 11 14  6 13]
 [ 7  9 12  8 12]
 [16  7 10 11 11]]


In [39]:
print(type(c))
print(c.shape)

<class 'numpy.ndarray'>
(5, 5)
