In [1]:
print("Hello")

Hello


# Get the numpy version and show numpy build configuration

In [2]:
import numpy as np
print(np.__version__)
#print(np.show_config())

1.18.1


# 2. Write a NumPy program to  get help on the add function.

In [41]:

print(np.info(np.arange))

#help()

arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1] - out[i]``

In [5]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

# 3. Write a NumPy program to test whether none of the elements of a given array is zero.

In [6]:
x = np.array([1, 2, 3, 4])
print(x)
print("Checking if all the element is non Zero : ")
print(np.all(x))

[1 2 3 4]
Checking if all the element is non Zero : 
True


In [8]:
x = np.array([0, 2, 3, 4])
print(x)
print("Checking if all the element is non Zero : ")
print(np.all(x))

[0 2 3 4]
Checking if all the element is non Zero : 
False


# 4. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [10]:
x = np.array([0, 0, 0, 4])
print(x)
print("Checking if any of  the element is non Zero : ")
print(np.any(x))

[0 0 0 4]
Checking if any of  the element is non Zero : 
True


In [12]:
x = np.array([0, 0, 0, 0])
print(x)
print("Checking if any of  the element is non Zero : ")
print(np.any(x))

[0 0 0 0]
Checking if any of  the element is non Zero : 
False


In [13]:
a=np.array([1,2,np.nan , np.inf])
# test if any of the number is infifnity
print(np.isinf(a))
print(np.isnan(a))

[False False False  True]
[False False  True False]


In [17]:
y=np.nan_to_num(a)
print(a)
print(y)

[ 1.  2. nan inf]
[1.00000000e+000 2.00000000e+000 0.00000000e+000 1.79769313e+308]


In [25]:
x=np.array([2,3,5,4])
print(x.itemsize)
print(x.size)
print(x)


4
4
[2 3 5 4]


In [34]:
y=list(range(10))
print(y)

#x=range(10)
print(np.ones((3,3)))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : fl