In [5]:
n=int(input("Enter the number of rows in the pascale triangle"))
list1=[]
for i in range (n):
    temp_list=[]
    for j in range(i+1):
        if(j==0 or j==i):
            temp_list.append(1)
        else:
            temp_list.append(list1[i-1][j-1]+list1[i-1][j])
    list1.append(temp_list)
print(list1)

Enter the number of rows in the pascale triangle7
[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1], [1, 5, 10, 10, 5, 1], [1, 6, 15, 20, 15, 6, 1]]


In [6]:
#printing the pattern 
for i in range(n):
    for j in range(n-i-1):
        print(" ",end="")
    for k in range(i+1):
        print(list1[i][k],end=" ")
    print()

      1 
     1 1 
    1 2 1 
   1 3 3 1 
  1 4 6 4 1 
 1 5 10 10 5 1 
1 6 15 20 15 6 1 


In [9]:
#variable parameter 
def function(*parameters):
    print(parameters)
    #for i in parameters:
        #print(i)
function(10,20,"bhawesh")
function(10,20,"bhawesh",[10,20,30])


(10, 20, 'bhawesh')
(10, 20, 'bhawesh', [10, 20, 30])


In [14]:
# Some functions in python 
# absolute (abs(number))
print(abs(5))
print(abs(-5))
print(abs(-4.5))

5
5
4.5


In [17]:
#Round : round(num,placeb)
print(round(5.6397842,4))

5.6398


In [23]:
import math
print(math.floor(4.5))
print(math.ceil(4.5))
#trunch function returns integer part
print(math.trunc(4.6))
print(math.trunc(-4.6))


4
5
4
-4


In [40]:
#some more numeric function
print(math.e)
print(math.exp(10))
print(math.e**10)
x=math.e
print(math.log2(10))
print(math.sqrt(5))
print(math.sqrt(25))


2.718281828459045
22026.465794806718
22026.465794806703
3.321928094887362
2.23606797749979
5.0


In [44]:
print(math.pi)
print(math.modf(4.91))
print(math.radians(180))
print(math.degrees(math.pi))

3.141592653589793
(0.9100000000000001, 4.0)
3.141592653589793
180.0


In [55]:
#string function
str1="helo"
print(str1.capitalize())
str2="""
johnney johnney yes papa
eating sugar no papa 
telling lie no papa 
up above the world so high 
like a diamond in the sky
open your mouth ha ha ha """
print(str2.capitalize())
str2.count('papa')

Helo

johnney johnney yes papa
eating sugar no papa 
telling lie no papa 
up above the world so high 
like a diamond in the sky
open your mouth ha ha ha 


3

In [61]:
#endswith()
# checks wheter a string ends with a perticular letter or word or not

str3='google.com'
print(str3.endswith('.com'))
str3='india.gov.in'
print(str3.endswith('.gov.in'))

True
True


In [69]:
#some more string function
#find function to find the index of a letter or word in a string
print(str2)
print(str2.find('johnney'))
#split function to split the string 
print(str2.split())

#title function to capitalize every word of a string
print(str2.title())


johnney johnney yes papa
eating sugar no papa 
telling lie no papa 
up above the world so high 
like a diamond in the sky
open your mouth ha ha ha 
1
['johnney', 'johnney', 'yes', 'papa', 'eating', 'sugar', 'no', 'papa', 'telling', 'lie', 'no', 'papa', 'up', 'above', 'the', 'world', 'so', 'high', 'like', 'a', 'diamond', 'in', 'the', 'sky', 'open', 'your', 'mouth', 'ha', 'ha', 'ha']

Johnney Johnney Yes Papa
Eating Sugar No Papa 
Telling Lie No Papa 
Up Above The World So High 
Like A Diamond In The Sky
Open Your Mouth Ha Ha Ha 


In [78]:
#lower()
#islower()
#upper()
#isupper()
#swapcase ()
print(str1)
strr1=str1.upper()
print(strr1)
print(str1.islower())
print(strr1.isupper())
strr2=strr1.lower()
print(strr2)
print(str2)
str3=str2.swapcase()
print(str3)

helo
HELO
True
True
helo

johnney johnney yes papa
eating sugar no papa 
telling lie no papa 
up above the world so high 
like a diamond in the sky
open your mouth ha ha ha 

JOHNNEY JOHNNEY YES PAPA
EATING SUGAR NO PAPA 
TELLING LIE NO PAPA 
UP ABOVE THE WORLD SO HIGH 
LIKE A DIAMOND IN THE SKY
OPEN YOUR MOUTH HA HA HA 


In [86]:
#replace(" ", " ")
#isdigit()
#isalpha
print(str2)
print(str2.replace('johnney','johny sins'))
str1="hello"
print(str1.isalpha())
numbers='12456'
print(numbers.isdigit())


johnney johnney yes papa
eating sugar no papa 
telling lie no papa 
up above the world so high 
like a diamond in the sky
open your mouth ha ha ha 

johny sins johny sins yes papa
eating sugar no papa 
telling lie no papa 
up above the world so high 
like a diamond in the sky
open your mouth ha ha ha 
True
True


In [92]:
#strip() = remove extra charecters and alphabets from left and rigth both sides of the sring
#lstrip() = remove extra charecters and alphabets from only left  sides of the sring
#rstrip() = remove extra charecters and alphabets from only right  sides of the sring
str1="!!!!!Hello !!!!!!!"
print(str1)
str1=str1.strip('!')
print(str1)
print()

str1="!!!!!Hello !!!!!!!"
print(str1)
str1=str1.strip('!!!!!!!!!!!!!!')
print(str1)
print()

str1="!!!!!Hello !!!!!!!"
print(str1)
str1=str1.lstrip('!!!!!!!!!!!!!!')
print(str1)
print()

str1="!!!!!Hello !!!!!!!"
print(str1)
str1=str1.rstrip('!!!!!!!!!!!!!!')
print(str1)
print()





!!!!!Hello !!!!!!!
Hello 

!!!!!Hello !!!!!!!
Hello 

!!!!!Hello !!!!!!!
Hello !!!!!!!

!!!!!Hello !!!!!!!
!!!!!Hello 



In [95]:
import math
import sys
print(sys.path)


['C:\\Users\\Bhawesh\\Untitled Folder', 'C:\\Users\\Bhawesh\\anaconda3\\python37.zip', 'C:\\Users\\Bhawesh\\anaconda3\\DLLs', 'C:\\Users\\Bhawesh\\anaconda3\\lib', 'C:\\Users\\Bhawesh\\anaconda3', '', 'C:\\Users\\Bhawesh\\anaconda3\\lib\\site-packages', 'C:\\Users\\Bhawesh\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\Bhawesh\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Bhawesh\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\Bhawesh\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Bhawesh\\.ipython']


In [109]:
#file handelling
import os
os.getcwd()
f = open("test.txt",'w')
f.write("hii")
f.close()
f = open("test.txt",'r')
print(f.read())
f.close()

hii


In [127]:
f=open('test.txt')
print(f.read())
#f.close()
f=open('test.txt',mode='a')
f.write("\nI am Bhawesh ")
f.close()
f=open('test.txt')
print(f.read())
f.close()

hii
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
hii
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 


In [141]:
f=open('test.txt')
print(f.read())

hii
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 
I am Bhawesh 


In [142]:
print("hello")

hello


# file handelling

In [160]:
#open a file 
text_file=open("text.txt",mode='w')
text_file.write("Hello People")
text_file.close()
text_file=open("text.txt",mode='w')
text_file.write("welcome")
text_file.close()
text_file=open("text.txt")
text_file.read()
text_file=open("text.txt" ,mode='a')
text_file.write(" \nwelcome to amuls acadmey")
text_file.close()
text_file=open("text.txt")
print(text_file.read())
text_file.close()

welcome 
welcome to amuls acadmey


In [168]:
# renaming and removing the file
import os
#to remove and rename files sometimes we need to provide path names if python code files and the text file are not in the same directory
#os.rename("text.txt",'my_file.txt')
#os.remove("my_file.txt")
#getting the current working directory
print(os.getcwd())


C:\Users\Bhawesh\Untitled Folder


In [170]:
print(os.name)

nt


In [180]:
#os.mkdir("my_dir")

os.mkdir("C:\\Users\\Bhawesh\Desktop\\m_dir")


FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Bhawesh\\Desktop\\m_dir'

In [181]:
os.getcwd()

'C:\\Users\\Bhawesh\\Untitled Folder'

In [182]:
print(os.listdir())

['.ipynb_checkpoints', 'LIVE-1_Python.ipynb', 'my_dir', 'my_module.ipynb', 'numpy_practice.ipynb', 'numpy_practice_W3Schools.ipynb', 'practice_python_from_grrks_for_geeks.ipynb', 'pyhon_practice.ipynb', 'test.txt', 'Untitled.ipynb']


In [189]:
len(os.listdir("C:\\"))
#print(os.listdir("D:\\Movies"))
print(len(os.listdir("D:\\Movies")))

236


In [193]:
#os.rmdir("C:\\Users\\Bhawesh\Desktop\\m_dir")
print(os.listdir("C:\\Users\\Bhawesh\Desktop"))

['Desktop files', 'desktop.ini']


# exception Handelling

In [199]:
#generally standard errors , handelled by python internaly 
#ex:
import math
num=int(input("enter a number to calculate factorial"))
try:
    print(math.factorial(num))
except ValueError:
    print("factorial of ",num , " can not be calculated ")

enter a number to calculate factorial-5
factorial of  -5  can not be calculated 


In [198]:

num=int(input("enter a number to calculate factorial"))
print(math.factorial(num))

enter a number to calculate factorial0
1


In [202]:

num=int(input("enter a number to calculate factorial"))
try:
    print(math.factorial(num))
except:
   # raise ValueError("factorial of ",num , " can not be calculated ")
    print("factorial of ",num , " can not be calculated ")

enter a number to calculate factorial-5
factorial of  -5  can not be calculated 


In [204]:

num=int(input("enter a number to calculate factorial"))
try:
    print(math.factorial(num))
except:
   # raise ValueError("factorial of ",num , " can not be calculated ")
    print("factorial of ",num , " can not be calculated ")
finally:
    print("Good Bye")

enter a number to calculate factorial5
120
Good Bye


# OOP

In [207]:
class person :
    def display(self):
        print("Hello")
p1=person()
p1.display()
person().display()

Hello
Hello


In [216]:
class person :
    def __init__ (self,name):
        self.name=name
        self.age=20
    def display(self):
        print("Hello",self.name , "your age is ",self.age)
p1=person("bhawesh")
p1.display()



Hello bhawesh your age is  20


In [218]:
class pen:
    def __init__(self):
        self.name
        self.price
        self.colour
        self.length
        self.model
    def display_name():
        print("name of the pen : ", self.name)
    def display_price():
        print("price of the pen : ", self.price)
    def display_colour():
        print("colour of the pen : ", self.colour)
    def display_length():
        print("length of the pen : ", self.length)
    def display_model():
        print("model of the pen : ", self.model)
pen1=pen()    
pen1.name="Rmaex"
pen1.display_name()

AttributeError: 'pen' object has no attribute 'name'

In [2]:

print("Hello")

Hello


# Pattern printing

In [5]:
num=int(input("Enter number of rows "))
for i in range(1,num+1,2):
    print("* "*i)

Enter number of rows 10
* 
* * * 
* * * * * 
* * * * * * * 
* * * * * * * * * 


In [6]:
num=int(input("Enter number of rows "))
for i in range(1,num+1):
    print("* "*i)

Enter number of rows 10
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * * * 
* * * * * * * * 
* * * * * * * * * 
* * * * * * * * * * 


In [9]:
#no reduction in no of rows but 
num=int(input("Enter number of rows "))
k=1
for i in range(1,num+1):
    
    print("* "*k)
    k=k+2
# Did you noticed the difference between first and third pattern

Enter number of rows 5
* 
* * * 
* * * * * 
* * * * * * * 
* * * * * * * * * 


In [12]:
#pyramid Shape
num=int(input("Enter number of rows "))
for i in range(1,num+1):
    print(" "*(num-i),"* "*i)

Enter number of rows 10
          * 
         * * 
        * * * 
       * * * * 
      * * * * * 
     * * * * * * 
    * * * * * * * 
   * * * * * * * * 
  * * * * * * * * * 
 * * * * * * * * * * 


In [15]:
# Reverse pyramid Shape
num=int(input("Enter number of rows "))
for i in range(1,num+1):
    print(" "*i,"* "*(num-i)," "*i)

Enter number of rows 10
  * * * * * * * * *   
   * * * * * * * *    
    * * * * * * *     
     * * * * * *      
      * * * * *       
       * * * *        
        * * *         
         * *          
          *           
                      


In [16]:
#Diamond Shape
#pyramid Shape
num=int(input("Enter number of rows "))
for i in range(1,num+1):
    print(" "*(num-i),"* "*i)
#num=int(input("Enter number of rows "))
for i in range(1,num+1):
    print(" "*i,"* "*(num-i)," "*i)

Enter number of rows 10
          * 
         * * 
        * * * 
       * * * * 
      * * * * * 
     * * * * * * 
    * * * * * * * 
   * * * * * * * * 
  * * * * * * * * * 
 * * * * * * * * * * 
  * * * * * * * * *   
   * * * * * * * *    
    * * * * * * *     
     * * * * * *      
      * * * * *       
       * * * *        
        * * *         
         * *          
          *           
                      


In [17]:
num=int(input("Enter number of rows "))
for i in range(1,num+1):
    print("* "*(num-i)," "*i)

Enter number of rows 10
* * * * * * * * *   
* * * * * * * *    
* * * * * * *     
* * * * * *      
* * * * *       
* * * *        
* * *         
* *          
*           
           


In [25]:
# Print A
num=int(input("Enter number of rows "))
k=0
if(num%2==0):
    k=num+1
else:
    k=num
l=k
for i in range (0,l+1):
    print(" "*l,"*"," "*i,"*")
    l=l-i


Enter number of rows 10
            *  *
            *   *
           *    *
         *     *
      *      *
  *       *
 *        *
 *         *
 *          *
 *           *
 *            *
 *             *


In [ ]:
num=int(input("Enter number of rows "))
k=1
for i in range(1,num+1):
    print(" "*(num-i),"*"*(i*2))
    #print(" "*(num-k),"*"*k)
    #k=k+1
    
print("hello ")
print("hello ")
print("hello ")

In [10]:
num=int(input("Enter number of rows "))
k=1
print(" "*(num+1),"*")
for i in range(0,num+1):
    if(i==5):
        print(" "*(num-i),"* "*((i*2)-2))
    else:
        print(" "*(num-i),"*"," "*(i*2),"*")
    #print(" "*(num-k),"*"*k)
    #k=k+1
    
print("hello ")
print("hello ")
print("hello ")

Enter number of rows 10
            *
           *  *
          *    *
         *      *
        *        *
       *          *
      * * * * * * * * 
     *              *
    *                *
   *                  *
  *                    *
 *                      *
hello 
hello 
hello 


In [12]:
num=int(input("Enter number of rows "))
for i in range(0,num+1):
    for j in range(0,i+1):
        print(j,end=" ")
    print()


Enter number of rows 10
0 
0 1 
0 1 2 
0 1 2 3 
0 1 2 3 4 
0 1 2 3 4 5 
0 1 2 3 4 5 6 
0 1 2 3 4 5 6 7 
0 1 2 3 4 5 6 7 8 
0 1 2 3 4 5 6 7 8 9 
0 1 2 3 4 5 6 7 8 9 10 


In [13]:
num=int(input("Enter number of rows "))
for i in range(0,num+1):
    for j in range(0,num+1-i):
        print(j,end=" ")
    print()


Enter number of rows 10
0 1 2 3 4 5 6 7 8 9 10 
0 1 2 3 4 5 6 7 8 9 
0 1 2 3 4 5 6 7 8 
0 1 2 3 4 5 6 7 
0 1 2 3 4 5 6 
0 1 2 3 4 5 
0 1 2 3 4 
0 1 2 3 
0 1 2 
0 1 
0 


In [14]:
num=int(input("Enter number of rows "))
for i in range(0,num+1):
    k=str(i)+" "
    print(k*i)


Enter number of rows 10

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 
6 6 6 6 6 6 
7 7 7 7 7 7 7 
8 8 8 8 8 8 8 8 
9 9 9 9 9 9 9 9 9 
10 10 10 10 10 10 10 10 10 10 


In [16]:
num=int(input("Enter number of rows "))
for i in range(1,num+1):
    k=str(i)+" "
    print(k*(num-i))


Enter number of rows 10
1 1 1 1 1 1 1 1 1 
2 2 2 2 2 2 2 2 
3 3 3 3 3 3 3 
4 4 4 4 4 4 
5 5 5 5 5 
6 6 6 6 
7 7 7 
8 8 
9 



In [ ]:
num=int(input("Enter number of rows "))
for i in range(0,num+1):
    for j in range(0,i+1):
        print(j,end=" ")
    print()


In [36]:
num=int(input("Enter number of rows "))
for i in range(0,num+1):
    k=1
    List=[1]
    for j in range(i+1,0,-1):
        
        #print(k,end=" ")
        List.append(k)
        k=k*2
    for j in range(i,0,-1):
        print(List[j],end=" ")
    print()


Enter number of rows 10

1 
2 1 
4 2 1 
8 4 2 1 
16 8 4 2 1 
32 16 8 4 2 1 
64 32 16 8 4 2 1 
128 64 32 16 8 4 2 1 
256 128 64 32 16 8 4 2 1 
512 256 128 64 32 16 8 4 2 1 


In [40]:
num=int(input("Enter number of rows "))
for i in range(0,i):
    for j in range(i,-1,-1):
        print(2**j,end=" ")
    print()

Enter number of rows 10
1 
2 1 
4 2 1 
8 4 2 1 
16 8 4 2 1 
32 16 8 4 2 1 
64 32 16 8 4 2 1 


In [42]:
num=int(input("Enter number of rows "))
for i in range(0,num+1):
    for j in range(0,i):
        print(2**j,end=" ")
    for j in range(i,-1,-1):
        print(2**j,end=" ")
    print()
    

Enter number of rows 10
1 
1 2 1 
1 2 4 2 1 
1 2 4 8 4 2 1 
1 2 4 8 16 8 4 2 1 
1 2 4 8 16 32 16 8 4 2 1 
1 2 4 8 16 32 64 32 16 8 4 2 1 
1 2 4 8 16 32 64 128 64 32 16 8 4 2 1 
1 2 4 8 16 32 64 128 256 128 64 32 16 8 4 2 1 
1 2 4 8 16 32 64 128 256 512 256 128 64 32 16 8 4 2 1 
1 2 4 8 16 32 64 128 256 512 1024 512 256 128 64 32 16 8 4 2 1 


In [43]:
for i in range(i):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [56]:
# Numpy Exercises
import numpy as np
array=np.random.randint(1,10,(4,2),dtype=np.int16)
print(array)
print(array.shape)
print(array.size)
print("Total bytes consumed by the elements of array: ",array.nbytes)
print("The size of one element of array is : ", array.nbytes//array.size)
print("Length of one array element in byte : ",array.itemsize)
print(" Datatype of array : ",array.dtype)


[[3 2]
 [2 3]
 [8 2]
 [6 3]]
(4, 2)
8
Total bytes consumed by the elements of array:  16
The size of one element of array is :  2
Length of one array element in byte :  2
 Datatype of array :  int16


In [61]:
# Numpy Exercises
import numpy as np
array = np.empty([4,2], dtype = np.uint16)
print(array)
print(array.shape)
print(array.size)
print("Total bytes consumed by the elements of array: ",array.nbytes)
print("The size of one element of array is : ", array.nbytes//array.size)
print("Length of one array element in byte : ",array.itemsize)


[[49586 13888]
 [37724 43868]
 [36504  3648]
 [ 3905 34614]]
(4, 2)
8
Total bytes consumed by the elements of array:  16
The size of one element of array is :  2
Length of one array element in byte :  2


In [85]:
x=20
x.bit_length()

#print(x.to_bytes())
print(x.__dir__())
#print(x.__getattribute__('int'))

['__repr__', '__hash__', '__str__', '__getattribute__', '__lt__', '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__add__', '__radd__', '__sub__', '__rsub__', '__mul__', '__rmul__', '__mod__', '__rmod__', '__divmod__', '__rdivmod__', '__pow__', '__rpow__', '__neg__', '__pos__', '__abs__', '__bool__', '__invert__', '__lshift__', '__rlshift__', '__rshift__', '__rrshift__', '__and__', '__rand__', '__xor__', '__rxor__', '__or__', '__ror__', '__int__', '__float__', '__floordiv__', '__rfloordiv__', '__truediv__', '__rtruediv__', '__index__', '__new__', 'conjugate', 'bit_length', 'to_bytes', 'from_bytes', '__trunc__', '__floor__', '__ceil__', '__round__', '__getnewargs__', '__format__', '__sizeof__', 'real', 'imag', 'numerator', 'denominator', '__doc__', '__setattr__', '__delattr__', '__init__', '__reduce_ex__', '__reduce__', '__subclasshook__', '__init_subclass__', '__dir__', '__class__']


AttributeError: 'int' object has no attribute 'int'

In [94]:
array=np.arange(100,200,10,dtype=np.int16)
print(array)
print(len(array))
print(array.size)
print(array.nbytes)
array_new=np.reshape(array,(5,2))
print(array_new)

[100 110 120 130 140 150 160 170 180 190]
10
10
20
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [100]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray)
print(sampleArray[1:3,1:2])

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[55]
 [88]]


In [102]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
print(sampleArray[0::2,1::2])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


In [106]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2=np.array([[5,2,8],[1,4,7],[3,6,9]])
print(array1)
print()
print(array2)
array3=array1+array2
print()
print(array3)
print()
array3=array3**2
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[5 2 8]
 [1 4 7]
 [3 6 9]]

[[ 6  4 11]
 [ 5  9 13]
 [10 14 18]]

[[ 36  16 121]
 [ 25  81 169]
 [100 196 324]]


In [117]:
array1=np.arange(10,34,1)
print(array1)
array1=np.reshape(array1,(8,3))
print()
print(array1)
#print(np.split(array1,4))
print(array1.size)
print(array1.shape)
print("first : ")
print( array1[0:2,::])
print("second : ")
print( array1[2:4,::])
print("third : ")
print( array1[4:6,::])
print("fourth : ")
print( array1[6:,::])


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
24
(8, 3)
first : 
[[10 11 12]
 [13 14 15]]
second : 
[[16 17 18]
 [19 20 21]]
third : 
[[22 23 24]
 [25 26 27]]
fourth : 
[[28 29 30]
 [31 32 33]]


In [123]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
print()
#min accross axis 0
list1=[]
for i in range(0,3):
    list1.append(min(sampleArray[i,::]))
print(list1)
list1=[]
for i in range(0,3):
    list1.append(max(sampleArray[::,i]))
print(list1)

[[34 43 73]
 [82 22 12]
 [53 94 66]]

[34, 12, 53]
[82, 94, 73]


In [124]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn = np.array([[10,10,10]])
print(sampleArray)
print(newColumn)
del sampleArray[::,2]
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[10 10 10]]


ValueError: cannot delete array elements

In [125]:
print("EOE")
print("End Of Exercise")

EOE
End Of Exercise
