In [1]:
print("Hello")

Hello


### HI
--hbciac
--bvjacbj



In [2]:
import numpy as np
A=np.random.randint(10,size=(5,5))
print(A)

[[1 1 6 2 5]
 [2 6 9 8 9]
 [4 4 1 9 9]
 [2 9 1 8 1]
 [8 8 5 7 6]]


In [3]:
import numpy as np
B=np.random.randint(10,size=(5,5))
print(B)
print(B[2,2])
#print(A)

[[5 9 0 7 6]
 [3 2 9 4 8]
 [5 0 1 7 2]
 [5 3 3 9 2]
 [5 4 4 7 7]]
1


In [4]:
c=np.zeros((5,5),int)
print(c)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [5]:
for i in range(5):
    for j in range(5):
        c[i,j]=A[i,j]+B[i,j]
print(c)
print(A+B)
D=A+B


[[ 6 10  6  9 11]
 [ 5  8 18 12 17]
 [ 9  4  2 16 11]
 [ 7 12  4 17  3]
 [13 12  9 14 13]]
[[ 6 10  6  9 11]
 [ 5  8 18 12 17]
 [ 9  4  2 16 11]
 [ 7 12  4 17  3]
 [13 12  9 14 13]]


In [6]:
print(type(c))
print(c.shape)
print(c.size)

<class 'numpy.ndarray'>
(5, 5)
25


In [7]:
#dir(c)

In [8]:
#Adding two randomley generated 3D matrices 
D1=np.random.randint(0,10,(5,5,5))
D2=np.random.randint(0,10,(5,5,5))
print("D1 :",D1)
print("D2 :",D2)




D1 : [[[8 0 6 7 6]
  [4 2 6 6 2]
  [4 5 1 5 3]
  [0 6 1 5 6]
  [0 6 5 1 2]]

 [[9 3 9 1 5]
  [7 4 6 8 4]
  [8 9 8 6 9]
  [3 3 2 6 6]
  [1 9 9 3 0]]

 [[2 9 6 6 5]
  [9 1 9 7 0]
  [8 6 2 4 7]
  [0 2 8 9 0]
  [4 7 3 5 1]]

 [[3 6 2 1 7]
  [8 0 7 0 0]
  [4 3 3 1 8]
  [2 7 2 3 9]
  [2 4 9 6 1]]

 [[2 2 3 5 7]
  [6 2 1 5 4]
  [5 6 6 6 5]
  [9 0 5 6 1]
  [8 6 3 6 3]]]
D2 : [[[3 2 8 1 5]
  [8 9 5 1 1]
  [1 9 3 2 6]
  [4 3 6 1 3]
  [5 3 8 5 4]]

 [[7 5 8 5 8]
  [9 6 9 7 4]
  [0 3 6 7 2]
  [6 9 0 0 2]
  [6 2 9 9 4]]

 [[9 5 1 7 6]
  [7 9 0 9 0]
  [6 6 8 5 3]
  [7 3 3 0 0]
  [6 5 5 5 3]]

 [[6 1 5 1 0]
  [1 4 1 1 6]
  [0 9 3 6 3]
  [5 4 2 6 2]
  [4 0 5 0 7]]

 [[2 8 4 7 6]
  [7 3 0 9 5]
  [4 5 8 9 3]
  [1 8 5 6 2]
  [0 9 8 8 4]]]


In [9]:
print(D1.ndim)
print(D2.ndim)
print("Shape of D1 :",D1.shape)
print("Size of D1 :",D1.size)
print("Shape of D2 :",D2.shape)
print( "Shape of D1 :",D2.size)

3
3
Shape of D1 : (5, 5, 5)
Size of D1 : 125
Shape of D2 : (5, 5, 5)
Shape of D1 : 125


In [10]:
(r,c,d)=D1.shape
print(r)
s=np.zeros((5,5,5),int)
for i in range(r):
    for j in range(c):
        for k in range(d):
            s[i,j,k]=D1[i,j,k]+D2[i,j,k]
print(s)
s2=D1+D2
if(s[3,2,4]==s2[3,2,4]):
    print("Sum may be correct")

            

5
[[[11  2 14  8 11]
  [12 11 11  7  3]
  [ 5 14  4  7  9]
  [ 4  9  7  6  9]
  [ 5  9 13  6  6]]

 [[16  8 17  6 13]
  [16 10 15 15  8]
  [ 8 12 14 13 11]
  [ 9 12  2  6  8]
  [ 7 11 18 12  4]]

 [[11 14  7 13 11]
  [16 10  9 16  0]
  [14 12 10  9 10]
  [ 7  5 11  9  0]
  [10 12  8 10  4]]

 [[ 9  7  7  2  7]
  [ 9  4  8  1  6]
  [ 4 12  6  7 11]
  [ 7 11  4  9 11]
  [ 6  4 14  6  8]]

 [[ 4 10  7 12 13]
  [13  5  1 14  9]
  [ 9 11 14 15  8]
  [10  8 10 12  3]
  [ 8 15 11 14  7]]]
Sum may be correct


# Problem2 :
### --Find if a Given 2D point is inside or outside of a circle 


In [18]:
#print("Enter the Centre and radious of a circcle")
x1,y1,r=input("Enter the Centre and radious of a circcle").split()
print("x1: ",x1, " y1: ",y1 ," Radius: ",r)
x2,y2=input("Enter the points ").split()
print("x2: ",x2, " y2: ",y2)
distance=((int(x1)-int(x1))**2+(int(y1)-int(y2))**2)**0.5
if(distance<int(r)):
    print("point is inside the circle")
elif(distance==int(r)):
    print("point is on the circle")
else:
    print("point is outside the circle")


Enter the Centre and radious of a circcle0 0 25
x1:  0  y1:  0  Radius:  25
Enter the points 1 2
x2:  1  y2:  2
point is inside the circle


In [24]:
x1,y1,r=input("Enter the Centre and radious of a circcle").split()
x1=int(x1)
y1=int(y1)
r=int(r)
print("Data type of x1: ",type(x1), " Data type of y1: ",type(y1) ," Data type of Radius: ",type(r))

Enter the Centre and radious of a circcle0 0 25
Data type of x1:  <class 'int'>  Data type of y1:  <class 'int'>  Data type of Radius:  <class 'int'>


In [25]:
print(A)

[[1 1 6 2 5]
 [2 6 9 8 9]
 [4 4 1 9 9]
 [2 9 1 8 1]
 [8 8 5 7 6]]


In [36]:
print(np.reshape(A,25,'C'))
print(np.reshape(A,(5,-1),'C'))
#print(np.reshape(A,(-1,1),'C'))

[1 1 6 2 5 2 6 9 8 9 4 4 1 9 9 2 9 1 8 1 8 8 5 7 6]
[[1 1 6 2 5]
 [2 6 9 8 9]
 [4 4 1 9 9]
 [2 9 1 8 1]
 [8 8 5 7 6]]


# Exercise: take a tensor of size 4X5X6 and convert it into a tensor of vector  and matrix (10X12).

In [43]:
T=np.random.randint(1,10,(4,5,6))
print(T)
reshape_T=np.reshape(T,120)
print(reshape_T)
print(reshape_T.size)
mat_T=np.reshape(T,(10,12))
print(mat_T)
print(mat_T.shape)


[[[9 8 5 8 7 8]
  [2 8 7 3 4 2]
  [6 1 7 6 2 6]
  [7 7 6 1 7 6]
  [6 7 4 8 2 1]]

 [[5 5 6 4 9 8]
  [5 6 6 4 8 7]
  [6 6 4 9 3 3]
  [7 5 3 4 3 4]
  [4 5 4 3 7 5]]

 [[1 8 2 7 8 9]
  [9 5 4 2 2 5]
  [7 6 3 6 9 1]
  [8 3 7 5 4 4]
  [3 5 8 5 4 1]]

 [[6 9 8 3 3 7]
  [3 5 8 4 4 2]
  [6 8 3 8 4 9]
  [9 5 7 9 5 7]
  [8 9 4 8 8 6]]]
[9 8 5 8 7 8 2 8 7 3 4 2 6 1 7 6 2 6 7 7 6 1 7 6 6 7 4 8 2 1 5 5 6 4 9 8 5
 6 6 4 8 7 6 6 4 9 3 3 7 5 3 4 3 4 4 5 4 3 7 5 1 8 2 7 8 9 9 5 4 2 2 5 7 6
 3 6 9 1 8 3 7 5 4 4 3 5 8 5 4 1 6 9 8 3 3 7 3 5 8 4 4 2 6 8 3 8 4 9 9 5 7
 9 5 7 8 9 4 8 8 6]
120
[[9 8 5 8 7 8 2 8 7 3 4 2]
 [6 1 7 6 2 6 7 7 6 1 7 6]
 [6 7 4 8 2 1 5 5 6 4 9 8]
 [5 6 6 4 8 7 6 6 4 9 3 3]
 [7 5 3 4 3 4 4 5 4 3 7 5]
 [1 8 2 7 8 9 9 5 4 2 2 5]
 [7 6 3 6 9 1 8 3 7 5 4 4]
 [3 5 8 5 4 1 6 9 8 3 3 7]
 [3 5 8 4 4 2 6 8 3 8 4 9]
 [9 5 7 9 5 7 8 9 4 8 8 6]]
(10, 12)


In [45]:
print("A:",A)
print("B:",B)

A: [[1 1 6 2 5]
 [2 6 9 8 9]
 [4 4 1 9 9]
 [2 9 1 8 1]
 [8 8 5 7 6]]
B: [[5 9 0 7 6]
 [3 2 9 4 8]
 [5 0 1 7 2]
 [5 3 3 9 2]
 [5 4 4 7 7]]


In [46]:
print(A.shape)
print(B.shape)

(5, 5)
(5, 5)


In [49]:
hstacked_arr=np.hstack((A,B))
print(hstacked_arr)
print(hstacked_arr.shape)


[[1 1 6 2 5 5 9 0 7 6]
 [2 6 9 8 9 3 2 9 4 8]
 [4 4 1 9 9 5 0 1 7 2]
 [2 9 1 8 1 5 3 3 9 2]
 [8 8 5 7 6 5 4 4 7 7]]
(5, 10)


In [51]:
vstacked_arr=np.vstack((A,B))
print(vstacked_arr)
print(vstacked_arr.shape)

[[1 1 6 2 5]
 [2 6 9 8 9]
 [4 4 1 9 9]
 [2 9 1 8 1]
 [8 8 5 7 6]
 [5 9 0 7 6]
 [3 2 9 4 8]
 [5 0 1 7 2]
 [5 3 3 9 2]
 [5 4 4 7 7]]
(10, 5)


In [53]:
print(D1.shape)
print(D2.shape)

(5, 5, 5)
(5, 5, 5)


In [59]:
hstacked_arr=np.hstack((D1,D2))
#print(dstacked_arr)
print(hstacked_arr.shape)

(5, 10, 5)


In [60]:
vstacked_arr=np.vstack((D1,D2))
#print(dstacked_arr)
print(vstacked_arr.shape)

(10, 5, 5)


In [61]:
dstacked_arr=np.dstack((D1,D2))
#print(dstacked_arr)
print(dstacked_arr.shape)

(5, 5, 10)


# Exercise: Achieve the above tranaomfrs using numpy.concatenate

In [63]:
print(A.shape)
print(B.shape)

(5, 5)
(5, 5)


In [74]:
conc_arr=np.concatenate((D1,D2),axis=None)
print(conc_arr.shape)
print(type(conc_arr))

(250,)
<class 'numpy.ndarray'>


In [77]:
print("Hell")

Hell


# Problem-4: Find peaks/max in an list

In [78]:
A = [1,3,4,5,7,6,4,5,10,1]
print(A)

[1, 3, 4, 5, 7, 6, 4, 5, 10, 1]


In [80]:
#finding the max or peak in a list
for i in range (1,len(A)-1):
    if(A[i-1]<A[i]>A[i+1]):
        print(A[i])
if(A[0]>A[1] ):
    print(A[0])
elif( A[-1]>A[-2]):
    print(A[-1])

7
10


In [82]:
A=[11,3,4,5,7,6,4,5,10,15]
print(A)
#finding the max or peak in a list
for i in range (1,len(A)-1):
    if(A[i-1]<A[i]>A[i+1]):
        print(A[i])
if(A[0]>A[1] ):
    print(A[0])
if( A[-1]>A[-2]):
    print(A[-1])

[11, 3, 4, 5, 7, 6, 4, 5, 10, 15]
7
11
15
